# Shell variables
# Generated by 'wal'
wallpaper='/home/splin/wallpaper/lofoten1.jpg'

# Special
background='#130914'
foreground='#e6e4cb'
cursor='#e6e4cb'

# Colors
color0='#130914'
color1='#2A588E'
color2='#5D6D8D'
color3='#69959B'
color4='#5FAAA3'
color5='#9BA39E'
color6='#A8D0B0'
color7='#e6e4cb'
color8='#a19f8e'
color9='#2A588E'
color10='#5D6D8D'
color11='#69959B'
color12='#5FAAA3'
color13='#9BA39E'
color14='#A8D0B0'
color15='#e6e4cb'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
