# Shell variables
# Generated by 'wal'
wallpaper='/home/hyprlin/wallpaper/miracleOS_light.jpg'

# Special
background='#0A000B'
foreground='#f4c8d7'
cursor='#f4c8d7'

# Colors
color0='#0A000B'
color1='#B26EC2'
color2='#C47BC2'
color3='#F56BFB'
color4='#DF8CB9'
color5='#D789C1'
color6='#EB97C1'
color7='#f4c8d7'
color8='#aa8c96'
color9='#B26EC2'
color10='#C47BC2'
color11='#F56BFB'
color12='#DF8CB9'
color13='#D789C1'
color14='#EB97C1'
color15='#f4c8d7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
