--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/splin/wallpaper/lofoten1.jpg"

-- Special
background="#130914"
foreground="#e6e4cb"
cursor="#e6e4cb"

-- Colors
color0="#130914"
color1="#2A588E"
color2="#5D6D8D"
color3="#69959B"
color4="#5FAAA3"
color5="#9BA39E"
color6="#A8D0B0"
color7="#e6e4cb"
color8="#a19f8e"
color9="#2A588E"
color10="#5D6D8D"
color11="#69959B"
color12="#5FAAA3"
color13="#9BA39E"
color14="#A8D0B0"
color15="#e6e4cb"
