--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/hyprlin/wallpaper/miracleOS_light.jpg"

-- Special
background="#0A000B"
foreground="#f4c8d7"
cursor="#f4c8d7"

-- Colors
color0="#0A000B"
color1="#B26EC2"
color2="#C47BC2"
color3="#F56BFB"
color4="#DF8CB9"
color5="#D789C1"
color6="#EB97C1"
color7="#f4c8d7"
color8="#aa8c96"
color9="#B26EC2"
color10="#C47BC2"
color11="#F56BFB"
color12="#DF8CB9"
color13="#D789C1"
color14="#EB97C1"
color15="#f4c8d7"
